apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: gke-ingress-config
spec:
  healthCheck:
    type: HTTP
    port: 15020
    requestPath: /healthz/ready
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#client_ip_affinity
  sessionAffinity:
    affinityType: "CLIENT_IP"