apiVersion: networking.gke.io/v1beta1
kind: MultiClusterIngress
metadata:
  name: istio-ingressgateway-multicluster-ingress
spec:
  template:
    spec:
      backend:
       serviceName: istio-ingressgateway-multicluster-svc
       servicePort: 80
      tls:
      - secretName: frontend-cert-secret
