# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# PeerAuthenticaion must be STRICT mTLS.
# copied from https://github.com/GoogleCloudPlatform/bank-of-anthos-scripts/blob/master/applied-acm/peer-authn/template.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PeerAuthnStrict
metadata:
  name: peer-authn-strict
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["security.istio.io"]
        kinds: ["PeerAuthentication"]
    # Grafana pods complain otherwise
    excludedNamespaces: ["istio-system"]

---
# see https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/block-nodeport-services
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockNodePort
metadata:
  name: block-node-port
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
