# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    # for in-scope, deny external traffic by default
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          service:
            # ingress VIP for in-scope
            loadBalancerIP: ${IN_SCOPE_ISTIO_INGRESS_IP}
            ports:
              - name: https
                port: 443
                targetPort: 8443
  values:
    global:
      network: in-scope
      meshNetworks:
        in-scope:
          endpoints:
          - fromRegistry: Kubernetes
          gateways:
          - address: 0.0.0.0
            port: 443
        out-of-scope:
          endpoints:
          - fromRegistry: out-of-scope
          gateways:
          # ingress VIP for out-of-scope
          - address: ${OUT_OF_SCOPE_ISTIO_INGRESS_IP}
            port: 443
